<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>5629cd6b-c8f3-4d61-a606-9962ca89aece</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Imova.Contracts\Imova.Contracts.csproj" />
    <ProjectReference Include="..\Imova.Application\Imova.Application.csproj" />
    <ProjectReference Include="..\Imova.Infrastructure\Imova.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

</Project>
