// <auto-generated />
using System;
using Imova.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Imova.Infrastructure.Migrations
{
    [DbContext(typeof(ImovaDbContext))]
    [Migration("20260925112643_AddProximitiesAndDropNearbyAmenities")]
    partial class AddProximitiesAndDropNearbyAmenities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Imova.Application.Common.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Imova.Domain.Amenities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("ApplicablePropertyTypes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LabelRo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4 },
                            Category = "Leisure",
                            Key = "parking",
                            LabelRo = "Parcare"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            ApplicablePropertyTypes = new[] { 1, 2, 6 },
                            Category = "General",
                            Key = "balcony",
                            LabelRo = "Balcon/Logie"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            ApplicablePropertyTypes = new[] { 1, 4 },
                            Category = "General",
                            Key = "elevator",
                            LabelRo = "Ascensor"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4, 6 },
                            Category = "Comfort",
                            Key = "air_conditioning",
                            LabelRo = "Aer condiționat"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4, 6 },
                            Category = "Comfort",
                            Key = "furnished",
                            LabelRo = "Mobilat"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            ApplicablePropertyTypes = new[] { 1, 2 },
                            Category = "Leisure",
                            Key = "garage",
                            LabelRo = "Garaj"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Leisure",
                            Key = "yard",
                            LabelRo = "Curte"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            ApplicablePropertyTypes = new[] { 4, 6 },
                            Category = "General",
                            Key = "autonomous_heating",
                            LabelRo = "Încălzire autonomă"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            ApplicablePropertyTypes = new[] { 4, 6 },
                            Category = "General",
                            Key = "centralized_heating",
                            LabelRo = "Încălzire centralizată"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000a"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4 },
                            Category = "Security",
                            Key = "wheelchair_access",
                            LabelRo = "Acces pentru scaun cu rotile"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000b"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4 },
                            Category = "Leisure",
                            Key = "storage_room",
                            LabelRo = "Debara"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000c"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4, 5 },
                            Category = "Security",
                            Key = "video_surveillance",
                            LabelRo = "Supraveghere video"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000d"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4, 6 },
                            Category = "Comfort",
                            Key = "internet",
                            LabelRo = "Internet"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000e"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Comfort",
                            Key = "fireplace",
                            LabelRo = "Șemineu"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000f"),
                            ApplicablePropertyTypes = new[] { 1, 2 },
                            Category = "Comfort",
                            Key = "underfloor_heating",
                            LabelRo = "Încălzire în pardoseală"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            ApplicablePropertyTypes = new[] { 1, 2 },
                            Category = "Comfort",
                            Key = "smart_home",
                            LabelRo = "Sistem casă inteligentă"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000011"),
                            ApplicablePropertyTypes = new[] { 1, 2, 6 },
                            Category = "Comfort",
                            Key = "appliances",
                            LabelRo = "Cu tehnică de uz casnic"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000012"),
                            ApplicablePropertyTypes = new[] { 1, 2, 6 },
                            Category = "Comfort",
                            Key = "cable_tv",
                            LabelRo = "Televiziune prin cablu"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000013"),
                            ApplicablePropertyTypes = new[] { 1, 2 },
                            Category = "Comfort",
                            Key = "landline",
                            LabelRo = "Telefon fix"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000014"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4 },
                            Category = "Security",
                            Key = "intercom",
                            LabelRo = "Interfon"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000015"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4, 5 },
                            Category = "Security",
                            Key = "alarm_system",
                            LabelRo = "Sistem de alarmă"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000016"),
                            ApplicablePropertyTypes = new[] { 2, 5 },
                            Category = "Security",
                            Key = "remote_gate",
                            LabelRo = "Poartă cu telecomandă"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000017"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Leisure",
                            Key = "sauna",
                            LabelRo = "Saună"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000018"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Leisure",
                            Key = "basement",
                            LabelRo = "Beci/subsol"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000019"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Leisure",
                            Key = "gazebo",
                            LabelRo = "Foișor"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000001a"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Leisure",
                            Key = "pool",
                            LabelRo = "Piscină"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000001b"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Leisure",
                            Key = "terrace",
                            LabelRo = "Terasă"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000001c"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Leisure",
                            Key = "garden",
                            LabelRo = "Grădină/seră"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000001d"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Leisure",
                            Key = "staff_room",
                            LabelRo = "Cameră pentru personal/pază"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000001e"),
                            ApplicablePropertyTypes = new[] { 2, 4 },
                            Category = "Leisure",
                            Key = "backup_generator",
                            LabelRo = "Generator de rezervă"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000001f"),
                            ApplicablePropertyTypes = new[] { 2 },
                            Category = "Leisure",
                            Key = "water_purification",
                            LabelRo = "Sistem de purificare a apei"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000020"),
                            ApplicablePropertyTypes = new[] { 1, 2, 6 },
                            Category = "Comfort",
                            Key = "dishwasher",
                            LabelRo = "Mașină de spălat vase"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000021"),
                            ApplicablePropertyTypes = new[] { 1, 2 },
                            Category = "Security",
                            Key = "armored_door",
                            LabelRo = "Ușă blindată"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000022"),
                            ApplicablePropertyTypes = new[] { 1 },
                            Category = "General",
                            Key = "storage_annex",
                            LabelRo = "Anexă/boxă"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000023"),
                            ApplicablePropertyTypes = new[] { 1, 4 },
                            Category = "General",
                            Key = "separate_entrance",
                            LabelRo = "Intrare separată"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000024"),
                            ApplicablePropertyTypes = new[] { 1, 2, 4 },
                            Category = "Comfort",
                            Key = "panoramic_windows",
                            LabelRo = "Geamuri panoramice"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000025"),
                            ApplicablePropertyTypes = new[] { 1 },
                            Category = "Comfort",
                            Key = "separate_living_room",
                            LabelRo = "Living separat"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000026"),
                            ApplicablePropertyTypes = new[] { 1, 4, 6 },
                            Category = "Comfort",
                            Key = "thermopane_windows",
                            LabelRo = "Geamuri termopan"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000027"),
                            ApplicablePropertyTypes = new[] { 3, 5 },
                            Category = "Security",
                            Key = "guarded",
                            LabelRo = "Pază"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000002a"),
                            ApplicablePropertyTypes = new[] { 5 },
                            Category = "General",
                            Key = "electricity",
                            LabelRo = "Electricitate"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000002b"),
                            ApplicablePropertyTypes = new[] { 6 },
                            Category = "Comfort",
                            Key = "kitchen_access",
                            LabelRo = "Acces la bucătărie"
                        });
                });

            modelBuilder.Entity("Imova.Domain.Favorites.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId", "ListingId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Imova.Domain.Listings.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RentalDetails")
                        .HasColumnType("jsonb");

                    b.Property<string>("SaleDetails")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Status");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Imova.Domain.Listings.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlobName")
                        .IsUnique();

                    b.HasIndex("ListingId");

                    b.ToTable("Photos", (string)null);
                });

            modelBuilder.Entity("Imova.Domain.Locations.ChisinauSector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ChisinauSectors", (string)null);
                });

            modelBuilder.Entity("Imova.Domain.Locations.Localitate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("NameRo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameRu")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("ParentLocalityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocalityId");

                    b.HasIndex("RaionId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("Localitati", (string)null);
                });

            modelBuilder.Entity("Imova.Domain.Locations.PropertyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ChisinauSectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChisinauSectorName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("LocalitateId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocalitateName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RaionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RaionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChisinauSectorId");

                    b.HasIndex("LocalitateId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("RaionId");

                    b.ToTable("PropertyLocations");
                });

            modelBuilder.Entity("Imova.Domain.Locations.Raion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("LocalityLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NameRo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameRu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("Raioane", (string)null);
                });

            modelBuilder.Entity("Imova.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Condition")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAreaM2")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("TypeSpecificAttributes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.HasIndex("PropertyType");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Imova.Domain.Properties.PropertyAmenity", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.HasKey("PropertyId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PropertyAmenities", (string)null);
                });

            modelBuilder.Entity("Imova.Domain.Properties.PropertyProximity", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProximityId")
                        .HasColumnType("uuid");

                    b.HasKey("PropertyId", "ProximityId");

                    b.HasIndex("ProximityId");

                    b.ToTable("PropertyProximities", (string)null);
                });

            modelBuilder.Entity("Imova.Domain.Proximities.Proximity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("ApplicablePropertyTypes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LabelRo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Proximities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "kindergarten",
                            LabelRo = "Grădiniță"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "school",
                            LabelRo = "Școală"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "supermarket",
                            LabelRo = "Supermarket / magazin alimentar"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000004"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "pharmacy",
                            LabelRo = "Farmacie"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000005"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "public_transport",
                            LabelRo = "Stație transport public"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000006"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "park",
                            LabelRo = "Parc / zonă verde"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000007"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "city_center",
                            LabelRo = "Centrul orașului"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000008"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "hospital",
                            LabelRo = "Spital / policlinică"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000009"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "farmers_market",
                            LabelRo = "Piață agroalimentară"
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-00000000000a"),
                            ApplicablePropertyTypes = new[] { 1, 2, 3, 4, 5, 6 },
                            Key = "bank",
                            LabelRo = "Bancă / bancomat"
                        });
                });

            modelBuilder.Entity("Imova.Domain.Publishers.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PublisherType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PublisherType")
                        .IsUnique();

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Imova.Domain.Favorites.Favorite", b =>
                {
                    b.HasOne("Imova.Domain.Listings.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imova.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imova.Domain.Listings.Listing", b =>
                {
                    b.HasOne("Imova.Domain.Properties.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imova.Domain.Publishers.Publisher", null)
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Imova.Domain.Listings.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("PriceCurrency");

                            b1.Property<bool>("IsNegotiable")
                                .HasColumnType("boolean")
                                .HasColumnName("PriceIsNegotiable");

                            b1.Property<decimal>("PriceEur")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("PriceEur");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Imova.Domain.Locations.Localitate", b =>
                {
                    b.HasOne("Imova.Domain.Locations.Localitate", null)
                        .WithMany()
                        .HasForeignKey("ParentLocalityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Imova.Domain.Locations.Raion", null)
                        .WithMany()
                        .HasForeignKey("RaionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Imova.Domain.Locations.PropertyLocation", b =>
                {
                    b.HasOne("Imova.Domain.Locations.ChisinauSector", null)
                        .WithMany()
                        .HasForeignKey("ChisinauSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Imova.Domain.Locations.Localitate", null)
                        .WithMany()
                        .HasForeignKey("LocalitateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Imova.Domain.Locations.Raion", null)
                        .WithMany()
                        .HasForeignKey("RaionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Imova.Domain.Properties.Property", b =>
                {
                    b.HasOne("Imova.Domain.Locations.PropertyLocation", null)
                        .WithOne()
                        .HasForeignKey("Imova.Domain.Properties.Property", "LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Imova.Domain.Properties.PropertyAmenity", b =>
                {
                    b.HasOne("Imova.Domain.Amenities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Imova.Domain.Properties.Property", null)
                        .WithMany("Amenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imova.Domain.Properties.PropertyProximity", b =>
                {
                    b.HasOne("Imova.Domain.Properties.Property", null)
                        .WithMany("Proximities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imova.Domain.Proximities.Proximity", null)
                        .WithMany()
                        .HasForeignKey("ProximityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Imova.Domain.Publishers.Publisher", b =>
                {
                    b.HasOne("Imova.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Imova.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Imova.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Imova.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Imova.Application.Common.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Imova.Domain.Properties.Property", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Proximities");
                });
#pragma warning restore 612, 618
        }
    }
}
